[package]
name = "test-sys"
version = "0.0.0" 
edition = "2021"
repository = "https://github.com/joe-stifler/cargo-tests"

exclude = ["/target", "/Cargo.lock"]
include = ["/src", "build.rs", "Cargo.toml", "*.so*"]

[dependencies]
