name: Release

on:
  push:
    branches:
      - main

jobs:
  test-check-lint:
    uses: ./.github/workflows/test-check-lint.yml

  release:
    name: Build Publish Library - Linux-x86_64
    runs-on: ubuntu-latest
    needs: [test-check-lint]
    environment: deploy
    container:
      image: rust:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - run: git config --global --add safe.directory $(realpath .)

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y libclang-dev
          cargo install --version 0.60.1 bindgen
          rustup component add rustfmt

      - name: Semantic relase
        run: |
          npm install semantic-release
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
