name: Test-Check-Lint

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-rust:
    name: Rust Sys Crate
    runs-on: ubuntu-latest # TODO: change to self-hosted runner
    container:
      image: rust:slim-buster # TODO: change to blitzar image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y libclang-dev
          cargo install --version 0.60.1 bindgen
          rustup component add rustfmt

      - name: Run rust tests
        run: cargo test --manifest-path rust/tests/Cargo.toml
